print("Hello, World!")
print("Whats your Name?")
yourName = input()
print("Its good to met you, "+ yourName)
print("The length of your name is: ")
print(len(yourName))
print("Whats your age?")
yourAge = int(input())
print("you will be " + str(yourAge + 1) + " in a year.")
